services:
  - type: web
    name: quizz-app
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/ping
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: jdbc:oracle:thin:@quizdb_low?TNS_ADMIN=/tmp/quizz-app-wallet
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
