-- Flyway V1, Oracle Database 19c+.
-- Place at src/main/resources/db/migration/V1__create_quiz_schema.sql.
-- Run against an empty application schema. Oracle DDL commits implicitly.

CREATE TABLE category (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code VARCHAR2(40 CHAR) NOT NULL,
    name VARCHAR2(120 CHAR) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_code UNIQUE (code)
);

CREATE TABLE app_user (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    email VARCHAR2(320 CHAR) NOT NULL,
    display_name VARCHAR2(150 CHAR),
    role_code VARCHAR2(10 CHAR) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role_code IN ('ADMIN', 'USER')),
    CONSTRAINT ck_app_user_email_lower CHECK (email = LOWER(email))
);

CREATE TABLE quiz (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    category_id NUMBER(19) NOT NULL,
    created_by_user_id NUMBER(19) NOT NULL,
    title VARCHAR2(200 CHAR) NOT NULL,
    status VARCHAR2(12 CHAR) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quiz PRIMARY KEY (id),
    CONSTRAINT fk_quiz_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_quiz_creator FOREIGN KEY (created_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_quiz_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);

CREATE TABLE quiz_version (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    quiz_id NUMBER(19) NOT NULL,
    version_no NUMBER(10) NOT NULL,
    schema_version NUMBER(3) NOT NULL,
    duration_minutes NUMBER(5) NOT NULL,
    content_json CLOB NOT NULL,
    status VARCHAR2(12 CHAR) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_quiz_version PRIMARY KEY (id),
    CONSTRAINT fk_qv_quiz FOREIGN KEY (quiz_id) REFERENCES quiz (id),
    CONSTRAINT uq_qv_number UNIQUE (quiz_id, version_no),
    CONSTRAINT uq_qv_id_quiz UNIQUE (id, quiz_id),
    CONSTRAINT ck_qv_version_positive CHECK (version_no > 0),
    CONSTRAINT ck_qv_schema_positive CHECK (schema_version > 0),
    CONSTRAINT ck_qv_duration_positive CHECK (duration_minutes > 0),
    CONSTRAINT ck_qv_json CHECK (content_json IS JSON),
    CONSTRAINT ck_qv_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_qv_publication CHECK (
        (status = 'DRAFT' AND published_at IS NULL)
        OR (status IN ('ACTIVE', 'RETIRED') AND published_at IS NOT NULL)
    )
);

-- Only one version of a quiz may be ACTIVE. Non-ACTIVE rows produce NULL keys.
CREATE UNIQUE INDEX uq_qv_one_active ON quiz_version (
    CASE WHEN status = 'ACTIVE' THEN quiz_id END
);

CREATE TABLE attempt (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    quiz_id NUMBER(19) NOT NULL,
    quiz_version_id NUMBER(19) NOT NULL,
    retake_grant_id NUMBER(19),
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    submitted_at TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR2(12 CHAR) NOT NULL,
    submission_method VARCHAR2(10 CHAR),
    total_score NUMBER(10,2),
    max_score NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_attempt PRIMARY KEY (id),
    CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_attempt_qv FOREIGN KEY (quiz_version_id, quiz_id)
        REFERENCES quiz_version (id, quiz_id),
    CONSTRAINT uq_attempt_grant UNIQUE (retake_grant_id),
    CONSTRAINT ck_attempt_status CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'EXPIRED')),
    CONSTRAINT ck_attempt_method CHECK (submission_method IN ('USER', 'AUTO')),
    CONSTRAINT ck_attempt_deadline CHECK (expires_at > started_at),
    CONSTRAINT ck_attempt_max_score CHECK (max_score > 0),
    CONSTRAINT ck_attempt_score CHECK (total_score BETWEEN 0 AND max_score),
    CONSTRAINT ck_attempt_result CHECK (
        (status = 'SUBMITTED' AND submitted_at IS NOT NULL
            AND submission_method IS NOT NULL AND total_score IS NOT NULL)
        OR (status IN ('IN_PROGRESS', 'EXPIRED') AND submitted_at IS NULL
            AND submission_method IS NULL AND total_score IS NULL)
    )
);

-- Across all versions, each user gets just one initial attempt per quiz.
-- A retake must reference a grant; all granted attempts are excluded here.
CREATE UNIQUE INDEX uq_attempt_first ON attempt (
    CASE WHEN retake_grant_id IS NULL THEN user_id END,
    CASE WHEN retake_grant_id IS NULL THEN quiz_id END
);

CREATE TABLE attempt_answer (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    attempt_id NUMBER(19) NOT NULL,
    question_id VARCHAR2(80 CHAR) NOT NULL,
    response_json CLOB NOT NULL,
    points_awarded NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_attempt_answer PRIMARY KEY (id),
    CONSTRAINT fk_aa_attempt FOREIGN KEY (attempt_id) REFERENCES attempt (id),
    CONSTRAINT uq_aa_question UNIQUE (attempt_id, question_id),
    CONSTRAINT ck_aa_json CHECK (response_json IS JSON),
    CONSTRAINT ck_aa_points CHECK (points_awarded >= 0)
);

CREATE TABLE retake_grant (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    source_attempt_id NUMBER(19) NOT NULL,
    granted_by_user_id NUMBER(19) NOT NULL,
    granted_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_retake_grant PRIMARY KEY (id),
    CONSTRAINT fk_rg_source FOREIGN KEY (source_attempt_id) REFERENCES attempt (id),
    CONSTRAINT fk_rg_admin FOREIGN KEY (granted_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_rg_revocation CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);

-- Added after both tables exist because ATTEMPT and RETAKE_GRANT refer to each other.
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_grant
    FOREIGN KEY (retake_grant_id) REFERENCES retake_grant (id);

-- Query paths for quiz lists and attempts/results. The UNIQUE constraints above
-- already provide indexes for (quiz_id, version_no), (attempt_id, question_id), etc.
CREATE INDEX ix_quiz_category ON quiz (category_id);
CREATE INDEX ix_attempt_user_started ON attempt (user_id, started_at);
CREATE INDEX ix_attempt_quiz_started ON attempt (quiz_id, started_at);
CREATE INDEX ix_rg_source ON retake_grant (source_attempt_id);
